version: "3.7"

services:
  api:
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8080:8080
    command: air main api
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_started
  migrate:
    build: .
    volumes:
      - ./src:/usr/src/app
    command: app migration
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
