// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Entry struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Amount    int64     `json:"amount"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Transfer struct {
	ID         int32     `json:"id"`
	FromUserID int32     `json:"from_user_id"`
	ToUserID   int32     `json:"to_user_id"`
	Status     string    `json:"status"`
	Amount     int64     `json:"amount"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
