// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Transfer struct {
	ID           int32     `json:"id"`
	UserID       int32     `json:"user_id"`
	TransferType string    `json:"transfer_type"`
	Status       string    `json:"status"`
	Amount       int64     `json:"amount"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Balance   int64     `json:"balance"`
	Curreny   string    `json:"curreny"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
