// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Balance struct {
	ID      int32  `json:"id"`
	UserID  int32  `json:"user_id"`
	Balance string `json:"balance"`
}

type Transaction struct {
	ID              int32  `json:"id"`
	UserID          int32  `json:"user_id"`
	TransactionType string `json:"transaction_type"`
	Amount          string `json:"amount"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
